[ejs.landing]
updateAvailableTooltip = "업데이트 사용가능"
usernamePlaceholder = "닉네임"
usernameEditButton = "옵션"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "모장 서버 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "추가&nbsp;서비스"
newsButton = "뉴스"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않았습니다."
launchDetails = "잠시만 기다려주세요.."
newsNavigationStatus = "{currentPage} 중 {totalPages}"
newsErrorLoadSpan = "최신 뉴스를 불러오는 중.."
newsErrorFailedSpan = "뉴스를 불러오는 데에 실패했습니다."
newsErrorRetryButton = "다시시도"
newsErrorNoneSpan = "뉴스 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 잘못된 값"
loginEmailPlaceholder = "이메일 또는 닉네임"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊어버리셨습니까?"
loginRememberMeText = "이 장치를 기억할까요?"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정 생성이 필요한가요?"
loginPasswordDisclaimer1 = "비밀번호는 Mojang으로 전송되며 절대 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName} 은(는) Mojang AB. 와 관련이 없음을 알립니다."

[ejs.loginOptions]
loginOptionsTitle = "어떤 방식으로 로그인 할까요?"
loginWithMicrosoft = "마이크로소프트로 로그인"
loginWithMojang = "Mojang으로 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "이용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런처"
navAbout = "런처 정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 추가하거나 기존 계정을 관리합니다."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 마이크로소프트 계정 추가"
mojangAccount = "Mojang"
addMojangAccount = "+ Mojang 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 실행과 관련된 설정입니다."
gameResolutionTitle = "해상도"
launchFullscreenTitle = "전체화면으로 실행"
autoConnectTitle = "실행시 자동으로 서버에 연결"
launchDetachedTitle = "게임 실행시 런처와 분리"
launchDetachedDesc = "본 옵션을 비활성화하면 런처 종료시 게임도 같이 종료됩니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화합니다."
switchServerButton = "변경"
requiredMods = "필수 모드"
optionalMods = "선택 모드"
dropinMods = "끌어다 놓아 모드 추가"
addMods = "모드 추가"
dropinRefreshNote = "(F5 새로고침)"
shaderpacks = "셰이더팩"
shaderpackDesc = "셰이더를 활성화하거나 비활성화합니다. 셰이더는 높은 사양을 요구합니다. 여기에 커스텀 팩을 추가할 수 있습니다."
selectShaderpack = "셰이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "Java 구성 관리 (고급)."
memoryTitle = "메모리"
maxRAM = "최대 RAM"
minRAM = "최소 RAM"
memoryDesc = "권장 최소 RAM 용량은 3GB 입니다. 최소값과 최대값을 동일한 값으로 설정하면 렉을 감소시킬 수 있습니다."
memoryTotalTitle = "총 용량"
memoryAvailableTitle = "이용 가능"
javaExecutableTitle = "Java 실행 파일"
javaExecSelDialogTitle = "Java 실행 파일 선택"
javaExecSelButtonText = "파일 선택"
javaExecDesc = "Java 실행 파일은 게임 실행 전에 확인합니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong> 으로 끝나야 합니다."
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "런타임 시 JVM에 제공되는 옵션은 포함되지 않아야 합니다. <em>-Xms</em> 및 <em>-Xmx</em>은 포함되지 않아야 합니다."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처에 관한 설정입니다."
allowPrereleaseTitle = "사전 릴리스 업데이트 허용"
allowPrereleaseDesc = "사전 릴리스에는 완전히 테스트되거나 통합되지 않았을 수 있는 새로운 기능이 포함되어 있습니다.<br>사전 릴리스 버전을 사용하는 경우 정식 릴리스 버전은 사용 불가합니다."
dataDirectoryTitle = "데이터 경로"
selectDataDirectory = "데이터 경로 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일과 로컬 Java 설치는 데이터 디렉토리에 저장됩니다.<br>스크린샷 및 월드 저장은 해당 서버 구성에 대한 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "런처 정보"
aboutTabHeaderDesc = "현재 버전에 대한 정보를 확인하고 릴리스 노트를 제공합니다."
aboutTitle = "{appName}"
stableRelease = "Stable 버전"
versionText = "버전 "
sourceGithub = "Source (GitHub)"
support = "지원"
devToolsConsole = "DevTools Console"
releaseNotes = "릴리스 노트"
changelog = "변경사항"
noReleaseNotes = "릴리스 노트 없음"
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처에 대한 업데이트를 다운로드, 설치 및 검토합니다."
checkForUpdates = "업데이트 확인"
whatsNew = "새로운 기능"
updateReleaseNotes = "업데이트 릴리스 노트"

[ejs.waiting]
waitingText = "마이크로소프트에서 응답을 받아오는 중.."

[ejs.welcome]
continueButton = "계속하기"


[js.discord]
waiting = "클라이언트에서 응답을 받아오는 중중.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 Login"
microsoftLogoutTitle = "마이크로소프트 Logout"

[js.login]
login = "로그인"
loggingIn = "로그인 됨"
success = "성공"
tryAgain = "다시시도"

[js.login.error]
invalidValue = "* 올바르지 않은 값"
requiredValue = "* 필수"

[js.login.error.unknown]
title = "로그인 중 알 수 없는 오류"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "잠시만 기다려주세요.."
failureTitle = "실행 중 오류"
failureText = "See console (CTRL + Shift + i) for more details."
okay = "확인했습니다."

[js.landing.selectedAccount]
noAccountSelected = "계정이 선택되지 않음"

[js.landing.selectedServer]
noSelection = "서버가 선택되지 않음"
loading = "로딩중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인중.."
noCompatibleJava = "호환되는<br>Java 설치를 찾을 수 없습니다"
installJavaMessage = "Minecraft를 실행하려면 Java {major}의 64비트 설치가 필요합니다. 복사본을 설치하시겠습니까?"
installJava = "Java 설치"
installJavaManually = "수동 설치"
javaDownloadPrepare = "Java 다운로드 준비중.."
javaDownloadFailureTitle = "Java 다운로드 중 오류 발생"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "실행하려면<br>Java 가 필요합니다."
javaRequiredMessage = 'Java {major}를 실행하려면 유효한 x64 설치가 필요합니다.<br><br>Java를 수동으로 설치하는 방법에 대한 지침은 <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java ">Java 관리 가이드</a>를 참조하세요.'
javaRequiredDismiss = "이해했습니다."
javaRequiredCancel = "돌아가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포를 찾지 못했습니다."
javaDownloadCorruptedError = "다운로드된 JDK에 해시가 잘못되어 파일이 손상되었을 수 있습니다."
extractingJava = "Java 추출중"
javaInstalled = "설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보를 불러오는 중.."
fatalError = "치명적인 오류"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "잠시만 기다려주세요.."
errorDuringLaunchTitle = "실행 중 오류 발생"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "파일 무결성 검증중.."
errorDuringFileVerificationTitle = "파일 무결성 확인 중 오류 발생"
downloadingFiles = "파일 다운로드중.."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류 발생"
preparingToLaunch = "실행 준비중.."
launchingGame = "게임 실행중.."
launchWrapperNotDownloaded = "메인 파일인 LaunchWrapper를 제대로 다운로드하지 못했습니다. 그 결과 게임이 실행되지 않습니다.<br><br>이 문제를 해결하려면 바이러스 백신 소프트웨어를 일시적으로 끄고 게임을 다시 실행하세요.<br><br>시간이 되시면 <href=\\https://github.com/dscalzi/HeliosLauncher/issues \">문제를 제출하고 어떤 바이러스 백신 소프트웨어를 사용하는지 알려주세요. 저희가 그들에게 연락해서 문제를 해결해 보겠습니다."
doneEnjoyServer = "다 됐습니다. 이벤트를 즐겨주세요!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "새로운 뉴스가 있는지 확인중.."

[js.landing.discord]
loading = "게임을 불러오는중.."
joining = "게임에 참여하는중.."
joined = "혀누와 얼간이들 이벤트"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "실행 파일"
allFiles = "모든 파일"

[js.settings.mstfLogin]
errorTitle = "무언가 잘못되었습니다."
errorMessage = "Microsoft 인증에 실패했습니다. 다시 시도해 주세요."
okButton = "확인"

[js.settings.mstfLogout]
errorTitle = "무언가 잘못되었습니다."
errorMessage = "마이크로소프트 로그아웃에 실패했습니다. 다시 시도해 주세요."
okButton = "확인"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "계정 선택됨 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "! 경고 !<br>마지막 계정입니다."
lastAccountWarningMessage = "런처를 사용하려면 적어도 하나의 계정에 로그인해야 합니다. 이후에 다시 로그인해야 합니다.<br><br>로그아웃하시겠습니까?"
confirmButton = "맞습니다."
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "닉네임"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "계정 선택됨 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "삭제"
deleteFailedTitle = "사용자 모드 {fullName} 을 삭제하는 데에 실패했습니다."
deleteFailedMessage = "파일이 사용 중이 아닌지 확인한 후 다시 시도하세요."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "확인"

[js.settings.serverListing]
mainServer = "메인 서버"

[js.settings.java]
selectedJava = "선택됨: Java {version} ({vendor})"
invalidSelection = "올바르지 않은 선택"
requiresJava = "Java {major} x64. 가 필요합니다."
availableOptions = "Java {major}(HotSpot VM)에 사용할 수 있는 옵션"

[js.settings.about]
preReleaseTitle = "사전 릴리스"
stableReleaseTitle = "Stable 버전"
releaseNotesFailed = "릴리스 노트를 로드하지 못했습니다."

[js.settings.updates]
newReleaseTitle = "새로운 릴리스 사용 가능"
newPreReleaseTitle = "새로운 사전 릴리스 사용 가능"
downloadingButton = "다운로드중.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "최신 버전을 실행중입니다."
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "새로운 업데이트 확인중.."

[js.settings.msftLogin]
errorTitle = "마이크로소프트 로그인 실패"
errorMessage = "Microsoft 계정을 인증할 수 없습니다. 다시 시도해 주세요."
okButton = "확인"

[js.uibinder.startup]
fatalErrorTitle = "치명적인 오류: 배포 인덱스를 로드할 수 없음"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "닫기"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인 새로 고침 실패"
failedMessage = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다른 계정을 선택하거나 다시 로그인해 주세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다시 로그인해 주세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "새로운 업데이트 확인중..."
installNowButton = "지금 설치"
checkForUpdatesButton = "업데이트 확인"

[js.auth.microsoft.error]
noProfileTitle = "로그인 중 오류 발생:<br>프로필이 설정되지 않았습니다."
noProfileDesc = "Microsoft 계정에는 아직 Minecraft 프로필이 설정되어 있지 않습니다. 최근에 게임을 구매했거나 Xbox Game Pass를 통해 결제한 경우, <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>아직 게임을 구매하지 않았다면 <a href=\"https://minecraft.net/\">Minecraft.net</a>에서 프로필을 설정할 수도 있습니다."
noXboxAccountTitle = "로그인 중 오류 발생:<br>Xbox 계정이 아님"
noXboxAccountDesc = "Microsoft 계정에 Xbox 계정이 연결되어 있지 않습니다."
xblBannedTitle = "로그인 중 오류 발생:<br>Xbox Live 사용 불가능"
xblBannedDesc = "귀하의 Microsoft 계정은 Xbox Live를 사용할 수 없거나 금지된 국가에 있습니다."
under18Title = "로그인 중 오류 발생:<br>부모 승인 필요"
under18Desc = "18세 미만 사용자 계정은 성인이 가족에 추가해야 합니다."
unknownTitle = "알 수 없는 로그인 중 오류 발생"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
